### ISSUE TITLE
Change header separator color to Outlook default

### ISSUE THREAD

**Issue by cnmicha** [jeevatkm/ReplyWithHeaderMozilla#108]
Hi,

how do you think about changing the default value of the preference `extensions.replywithheader.header.separator.line.color` to `#1E1E1E` which is the header separator line color of Outlook?

What was the idea behind choosing the current default color (`#B5C4DF`)?

If you like, I can provide a pull request for this.

Thanks!

**Comment by jeevatkm** [comment]
@cnmicha When initially developed the RWH add-on that time I took a color code from Outlook. I think the Outlook client still uses that color. I can see with my macOS Outlook client v16.52 (21080801).

May I know where do you see a black color? web version?

**Comment by anttiisoaho** [comment]
Looks like Outlook has different default styles in Windows vs Mac.  While css is used in email sent by O365 Outlook, I simplified styling into html tags without css and ended up with below html snippet. I had 24 hour clock but otherwise regular US English settings. Note how separator line is produced by O365 Outlook client in Windows O365 Outlook client, with line color E1E1E1.  Below snippet is 100% similar than how replying or forwarding with O365 Outlook client in Windows.
```
<div><div style="border:none;border-top:solid #E1E1E1 1.0pt;padding:3.0pt 0cm 0cm 0cm">
<p style="margin-top:0;font-family:Calibri,sans-serif;font-size:11pt;">
<b>From:</b> Displayname_if_exist &lt;name@email.com&gt;<br>
<b>Sent:</b> Wednesday, October 11, 2023 17:32<br>
<b>To:</b> Displayname_if_exist &lt;name@email.com&gt;<br>
<b>Subject:</b> Email subject line</p>
</div></div>
```

**Comment by jeevatkm** [comment]
@anttiisoaho Thanks for providing the HTML string; it is helpful for understanding. 

@cnmicha @anttiisoaho I will change the header line default color to `#1E1E1E` on v3.0.0 onwards; until then, please use the RWH add-on options to change the color.

**Comment by anttiisoaho** [comment]
@jeevatkm just note the corrrect color value: `#E1E1E1` - I believe there was originally typo by @cnmicha. Additional notes:

- HTML snippet above is exactly what O365 Outlook client in Windows use for separator+headers, with note that I simplified headers text style from css into \<p\> tag
- From/To/Cc email addresses are inside < > and not inside [ ]

**Comment by jeevatkm** [comment]
@anttiisoaho Thanks. I will take care of it.

**Comment by jeevatkm** [comment]
@cnmicha @anttiisoaho I'm working on the WebExtension version of RWH. The branch is [here](https://github.com/jeevatkm/ReplyWithHeaderMozilla/tree/WebExtension). 

I require a sample string of the following in multiple languages for a `Plain Text` email.

**Reply**
```
On 4/27/24 5:58 PM, Thunderbird Add-ons wrote:
```

**Forward**
```
-------- Forwarded Message --------
Subject: Mozilla Add-on User Rating: ReplyWithHeader
Date: Sun, 28 Apr 2024 00:58:03 -0000
From: Thunderbird Add-ons <nobody@thunderbird.net>
To: jeeva@myjeeva.com
```

**Comment by anttiisoaho** [comment]
Plain text example from O365 (US English) if this is what you wanted - there is no difference in reply or forward so this applies to both:
```
-empty line, cursor blinks here when starting to reply or forward-
-empty line-
-----Original Message-----
From: Displayname_if_exist <name@email.com>
Sent: Tuesday, April 9, 2024 2:08 PM
To: Displayname_if_exist <name@email.com>
Subject: Email subject line
-empty line-
-forwarded or replied email content-
```

**Comment by jeevatkm** [comment]
Thanks, @anttiisoaho, for your help.

**Comment by jeevatkm** [comment]
@anttiisoaho @cnmicha Please see https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/103#issuecomment-2106526608, can you try it?

**Comment by anttiisoaho** [comment]
I finally managed to install fresh TB 128.0.1 with RWH 3.0.0 (release version), and have used that now for couple of days. In general looks good but there is also one bug. I also have some comments/suggestions:

- RWH locale resets to TB user interface locale at every TB start

In my case I like to keep TB user interface set to my local language (Finnish in my case), but set RWH to en-US to get "standard" written headers into email replies or forwards. I can set RWH locale in its settings, but it resets to TB user interface language at every TB start, which is a bug to my mind.

Other suggestions:

- Add option to enable or disable RWH menu button into mail tool bar
- Instead of timer, could there be checkmarks for some selected options, perhaps even change locale, I do understand changing something here then would be more permanent compared to temporary timer based change, however if users want to have button/menu available to change something on-the-fly, it would be anyway easy to see what is the current setting and change it even per email if so wanted

**Comment by jeevatkm** [comment]
@anttiisoaho I have created the new bug for the locale issue - https://github.com/jeevatkm/ReplyWithHeaderMozilla/issues/155

Regarding other suggestions: 
It will be challenging because RWH works when the user clicks on `Reply/Reply All/Forward,` there is a call listening to TB on the compose window show; it composes the email headers (and RWH features). RWH does not process/handle anything after that. I could experiment with it, but I won't be able to commit to it.

The timer functionally operates only on currently selected message and does not affect other email messages.

Introducing multiple disable/enable features could lead to issues and support questions.

RWH v3 has a new option to turn the feature on/off at the mail account level in addition to that timer enable option.

**Comment by anttiisoaho** [comment]
Thank you. Perhaps option to enable/disable (=visible/not visible) button would be relatively easy to implement into Options UI (?)  I'm after simplicity; most users don't need to change anything after extension properly configured, and for users who would like to e.g. use TB default reply/fwd style for some emails, could have button enabled (=visible).

**Comment by anttiisoaho** [comment]
> Perhaps option to enable/disable (=visible/not visible) button would be relatively easy

I thought hiding menu button or making it visible is easy but seems not to be. `messenger.messageDisplayAction.disable();` disables it in a way that button is grayed out but not fully hidden. There is obviously another extension which can be used to hide any of the buttons, also RWH, reorder etc.. but would have been nice to have such option "natively" in RWH extension.
