### ISSUE TITLE
Missing settings in v3.0.0

### ISSUE THREAD

**Issue by ygoe** [jeevatkm/ReplyWithHeaderMozilla#160]
Version 3.0.0 is missing a lot of the features and settings from 2.6.0. Is that intended? The reply headers look worse now and I'd like to fix that but can't really because the font size for example cannot be set anymore.

Also, all settings were reset with the new version. I guess that's because the settings are so incompatible and lacking.

The Thunderbird 128 upgrade caught me by surprise. Now I have to clean up the mess it created – again. I still have v115 on my laptop so I can at least compare what went wrong in the new version.

v2.6.0:
![grafik](https://github.com/user-attachments/assets/03c750e8-d125-44c0-b7b9-5d4b0553332f)

v3.0.0:
![grafik](https://github.com/user-attachments/assets/1e9c56ba-f4c7-47cc-aa72-1f17221c98e9)

**Comment by ygoe** [comment]
Plus, the reply header lacks a newline at the end. Now the header and the quoted content are really pushed together. With v2.6.0, there was an extra empty line between them which looked much better.

After some more testing, it looks like I'm mostly missing the font size setting. If I remember correctly that was added some time ago maybe because I was asking for it. Or was it the font?

An annoying workaround is this:

- Reply as usual
- Select the generated reply headers
- Decrease font size once (with the format toolbutton)
- Increase font size once again (now it's at the normal text size, which it wasn't before)
- Place the cursor at the end of the last header line
- Press Enter to get that extra newline

**Comment by jeevatkm** [comment]
@ygoe Thanks for reaching out. Let me provide the details.

You might have seen this in the release notes: "RWH v3 completely rewritten from the ground up using the Web/Mail Extension model."  
It took a lot of work to convert from the legacy to a web extension model; I had to leave certain functionalities behind because the web extension did not support them. So -

Header font and size align with current email document styles or TB style, depending on the email.

I will think of a way to bring a new line feature later.

**Comment by jeevatkm** [comment]
> Also, all settings were reset with the new version. I guess that's because the settings are so incompatible and lacking.

This is due to TB's Web Extension model, which has a specific way of handling settings. So, I have to start over with the new settings approach. In the future, the add-on upgrade will retain all settings the same as before.
For e.g., uninstalling an add-on will clear the settings from storage; this is a new behavior in TB.

**Comment by ygoe** [comment]
Oh, I haven't seen that. That explains the differences.

Let me say that the font style does not really align with the rest of the text. It seems to have an unspecified size which is different from all other text content that I can see and type by default. I haven't looked at it on the HTML source level but maybe I should do so to provide a better explanation of the problem.

The extra newline should be easy to do I guess. Sometimes you won't notice because the formats involve paragraph spacings, but sometimes they don't and it's really gapless from the headers to the quoted content.

**Comment by jeevatkm** [comment]
I will think of a way to address the extra new line part.

**Comment by ygoe** [comment]
Maybe [this line](https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/main/modules/compose.mjs#L179) just needs to be duplicated to also insert `positionBeforeEnd`?

**Comment by ygoe** [comment]
And in [this line](https://github.com/jeevatkm/ReplyWithHeaderMozilla/blob/main/modules/compose.mjs#L285) I guess the `font-size` should simply be removed. There's some strange CSS in there. Like the separator line's border and padding sizes specified in pt and cm... I'd rather expect a 1px border-width and unitless 0's there.

**Comment by ygoe** [comment]
Yes, confirmed. Shall I create a PR for it?

**Comment by PeterMacej** [comment]
Hi, just an idea. I agree with the PR #164 including all the comments. 
But wouldn't it be easier and more flexible to use CSS instead of the hard-coded formatting? I mean, currently, the generated code looks like:

``` html
<div id="rwhHeaders" style="border:none;border-top:solid lightgray 1.0pt;padding:3.0pt 0cm 0cm 0cm">
  <p style="margin:0cm;font-size:11.5pt"><span><b>From:</b> tom@abcd.com</span></p>
  <p style="margin:0cm;font-size:11.5pt"><span><b>To:</b> 'John' &lt;john@abcd.com&gt;</span></p>
  <p style="margin:0cm;font-size:11.5pt"><span><b>Date:</b> Tuesday, July 16, 2024 at 17:32 UTC+2</span></p>
  <p style="margin:0cm;font-size:11.5pt"><span><b>Subject:</b> Subject1</span></p>
</div>
```

The CSS version would be:

``` html
<style>
#rwhHeaders {
  border: none;
  border-top: solid lightgray 1.0pt;
  padding: 3.0pt 0cm 0cm 0cm;
}

#rwhHeaders p {
  margin: 0cm;
  font-size: 11.5pt;
}

#rwhHeaders span b {
  font-weight: bold;
}
</style>

<div id="rwhHeaders">
  <p><span><b>From:</b> tom@abcd.com</span></p>
  <p><span><b>To:</b> 'John' &lt;john@abcd.com&gt;</span></p>
  <p><span><b>Date:</b> Tuesday, July 16, 2024 at 17:32 UTC+2</span></p>
  <p><span><b>Subject:</b> Subject1</span></p>
</div>
```

I know that ` font-size: 11.5pt;` should be removed, the above is just an example. 
And then, you could add a simple text box in the settings named "CSS styling:" with the default value:
```
#rwhHeaders {
  border: none;
  border-top: solid lightgray 1.0pt;
  padding: 3.0pt 0cm 0cm 0cm;
}

#rwhHeaders p {
  margin: 0cm;
  font-size: 11.5pt;
}

#rwhHeaders span b {
  font-weight: bold;
}
```

You could add a button named "Reset to default" below it. And above it, I would add a text label with this info:
"The created HTML headers have the following format:
```
<div id="rwhHeaders">
  <p><span><b>From:</b> tom@abcd.com</span></p>
  <p><span><b>To:</b> 'John' &lt;john@abcd.com&gt;</span></p>
  <p><span><b>Date:</b> Tuesday, July 16, 2024 at 17:32 UTC+2</span></p>
  <p><span><b>Subject:</b> Subject1</span></p>
</div>
```
If you know what you are doing, you can customize the CSS styles below to make it look according to your needs. If anything goes wrong, reset the styles to their default value with the 'Reset to default' button.
"

Maybe this could be in a separete "Advanced" tab.

**Comment by ygoe** [comment]
Interesting idea. Just one hint: Those CSS styles apply to the entire message. If you and your other party both use this add-on, but with different class styles, you'll fight each other's header styles with each reply. 😀

I've added such CSS rules to my signature (because the old stationery add-on died) to fix spacings of lists and such, and it sometimes breaks styles of the content I quote. So I'd say that CSS stylesheets are probably more something for carefully designed newsletters, less for regular conversations. Even replying to such newsletters can look funny in your content because their styles spill over to it. For example if they center-align all text, then your reply may also be centered…

**Comment by jeevatkm** [comment]
Thanks, @ygoe, for adding appropriate details for CSS styles.

@PeterMacej Thanks for proposing an idea. However, tackling CSS styles on emails takes a lot of work to achieve reasonable outcomes. The RWH use case is straightforward: a block of HTML tags gets plugged into an appropriate spot in the email HTML tree, and an inline CSS style is the best way to tackle it.

**Comment by PeterMacej** [comment]
> The RWH use case is straightforward: a block of HTML tags gets plugged into an appropriate spot in the email HTML tree

I'aware of this. And my proposed approach does exactly the same. It simply injects an additional `<style>` HTML tag just before your DIV tag.

But I fully agree with @ygoe and his arguments. I now see that it was not a good idea.

**Comment by Fredrik-69** [comment]
The <style> HTML tag should never be used in sections of an email like in signatures or with plugins like this. Inline CSS is the only way to go.
