### ISSUE TITLE
Suggested improvements in Prefs

### ISSUE THREAD

**Issue by ofa-** [jeevatkm/ReplyWithHeaderMozilla#37]
- change date "format" labels in Prefs gui:
  Locale date format => Local timezone
  International date format (GMT) => International time (GMT)
- rename Prefs properties:
  date.format => date.timezone
  date.style => date.format
  (will break existing settings)
- use string properties (instead of int)
  and drop-downs instead of radio-buttons
  (would allow custom date/time format via config:  )
  (will break existing settings)

**Comment by jeevatkm** [comment]
@ofa- Thanks for the proposal. I will have a look.

**Comment by ofa-** [comment]
for the first item, you may check https://github.com/ofa-/ReplyWithHeaderMozilla/commit/b2768c26
(part of branch [ofa-:uniformize+simplify_radiogroups](https://github.com/jeevatkm/ReplyWithHeaderMozilla/compare/master...ofa-:uniformize+simplify_radiogroups?expand=1))

**Comment by ofa-** [comment]
Here is what it looks like on Ubuntu, with simplified styling internals.
(in this screenshot, please ignore the fact that I also moved the locale/lang button) 
![image](https://user-images.githubusercontent.com/1472525/36192689-f3280c98-1162-11e8-81c0-b91cd90f670b.png)

**Comment by jeevatkm** [comment]
It seems you're working on this otherwise please let me know. I have just merged my work into master. Please branch out fresh from master.

Please find my comment/suggestions:
* For Point No. 1 - please go ahead for string changes
* For Point No. 2 - It is important to provide backward compatibility. It can be achieved via fallback approach. First look for `date.timezone` if not found then look for `date.format`.
* For Point No. 2 - This is gonna be a issue `date.style => date.format`. For now we have to halt this change or pick some new name for setting.
* For Point No. 3 - For now we have to halt to this improvement. Its a new UI appearance and settings. It major step. We have to give it try on separate branch; see how its gonna look then we have to decide otherwise we have to postpone/skip this item.

Mostly existing users will be upgrading first (backward compatibility is important), I do not want spoil their experience with significant breaking changes. UI improvements is okay but configuration breaking might affect a lot For. eg: using `date.style => date.format` we have to choose some new settings name.

**Comment by jeevatkm** [comment]
@ofa- May I expect PR per above comments?

**Comment by ofa-** [comment]
@jeevatkm point 1: see #40

**Comment by ofa-** [comment]
considered done (point  n°1 done, plus internal cleanup done)
other suggested changes dropped, as they would break existing conf or require fallback implem.
