### ISSUE TITLE
language / region customizations

### ISSUE THREAD

**Issue by Masala-ms** [jeevatkm/ReplyWithHeaderMozilla#90]
Hi and thank you so much for this add-on, which seems to be the last (non-commoercial) one available that easily lets you adjust the reply header including the subject and works with TB 60.
Disclaimer: I'm not a developer and completely inexperienced with tb add-ons.

There's 2 things I'd like to adjust: First, exchange the word in the variables "From: ", "To: ", "Date: " and "Subject: ". Second, change the date format to something else (DD.MM.YYYY hh:mm [24h]).

I found other requests like this in the add-on comment section where you answered that you don't know if you'll find time for this, so I tried myself:

For the I did find the text identifiers in the core.js within the .xpi file, so I thought this would be an easy task, but I was unable to find the core.js anywhere else but in the .xpi file - there seems to be no RWH plugin folder in the tbird folder (%userprofile%\AppData\Roaming\Thunderbird\Profiles\xxxxxxxx.default). Where do I have to look? (Win10, roaming user profile in an organization).

For the date, I found different places where the format is being defined and I'm unsere where I have to change what.

I would appreciate any support with this!

**Comment by jeevatkm** [comment]
@Masala-ms Thank you for your appreciation. This is my personal project, I intended to keep it opensource.

As of today, RWH v2.1.0 works with TB 60.* and I have started studying the TB 68.0 updates for RWH #88. It seems lot of effort is needed to support TB 68.0. 

Previous I used to support a lot of customized required on header attribution and customization (header order, different date formats, etc.). People have plenty of personal taste. I ended up hard to support with my limited availability. That's why I have decided to stick to enhancing TB existing format and adding outlook format.

I would like to keep RWH add-on always active and does a good job supported feature set.

-----
Feel free customize the RWH add-on for your need. Development effort is not straight forward with TB. Repeated following these steps "modify code, build, install, test and uninstall" to development. 

Very simple TB development steps:
* Clone the RWH repo into your machine
* Use Editor like VS Code or Atom 
* Make changes to the code files
* Packing - 
   - *nix OS 
        * go to RWH source code directory and run`zip -r ../replywithheader@myjeeva.com-beta.xpi * -x ".*"` 
        * you will find the XPI file parent directory fo RWH source code
   - Windows 
        * go to the parent directory of RWH source code directory - Right-click and Compressed the RWH source code directory
        * Rename the zip file into `replywithheader@myjeeva.com-beta.xpi` including file extension
* Install
     - Go to TB and click the menu "Tools" -> "Add-on" -> click on "gear icon" -> choose "Install Add-on From File..." -> select the xpi from your hard drive
* Test your changes
* Uninstall the addon from add-on manager

Repeat the above steps until satisfied with your changes.

 Also, having a TB error console opened during development is helpful, open TB Error Console window by pressing: 
   - on macOS `Shift + Command + J` 
   - on Windows/Linux `Shift + Ctrl + J`

**Comment by Masala-ms** [comment]
Thanks for your reply!
Actually, the (very, very simple) solution for my issue was to switch the language in RWH ;-) I just hadn't put any attention to that setting before.
Thanks again and I hope, you'll have time to support TB 68+ soon.
